/** @type {import('next').NextConfig} */
const nextConfig = {
  trailingSlash: true,
  skipTrailingSlashRedirect: true,
  reactStrictMode: true,
  async redirects() {
    // Redirects específicos para posts antigos do blog
    // Adicione aqui apenas os slugs de posts que realmente existem
    return [
  { source: '/noticia-dos-tribunais-176', destination: '/blog/noticia-dos-tribunais-176', permanent: true },
  { source: '/marco-lilas-e-amarelo', destination: '/blog/marco-lilas-e-amarelo', permanent: true },
  { source: '/02-de-abril-dia-mundial-da-conscientizacao-do-autismo', destination: '/blog/02-de-abril-dia-mundial-da-conscientizacao-do-autismo', permanent: true },
  { source: '/22-de-marco-dia-mundial-da-agua', destination: '/blog/22-de-marco-dia-mundial-da-agua', permanent: true },
  { source: '/colesterol-ldl-hdl-vldl', destination: '/blog/colesterol-ldl-hdl-vldl', permanent: true },
  { source: '/teste-sorologico', destination: '/blog/teste-sorologico', permanent: true },
  { source: '/intolerancia-a-lactose', destination: '/blog/intolerancia-a-lactose', permanent: true },
  { source: '/anacli-kids', destination: '/blog/anacli-kids', permanent: true },
  { source: '/a-anacli-ja-comecou-suas-atividades-na-sobaby', destination: '/blog/a-anacli-ja-comecou-suas-atividades-na-sobaby', permanent: true },
  { source: '/resultados-online-e-coleta-domiciliar', destination: '/blog/resultados-online-e-coleta-domiciliar', permanent: true },
  { source: '/5-motivos-para-comecar-uma-atividade-fisica', destination: '/blog/5-motivos-para-comecar-uma-atividade-fisica', permanent: true },
  { source: '/feliz-pascoa', destination: '/blog/feliz-pascoa', permanent: true },
  { source: '/atendimento-especializado-para-a-criancada', destination: '/blog/atendimento-especializado-para-a-criancada', permanent: true },
  { source: '/6-exames-que-avaliam-a-tireoide', destination: '/blog/6-exames-que-avaliam-a-tireoide', permanent: true },
  { source: '/o-que-e-prolactina', destination: '/blog/o-que-e-prolactina', permanent: true },
  { source: '/pre-natal-completo-em-feira-de-santana', destination: '/blog/pre-natal-completo-em-feira-de-santana', permanent: true },
  { source: '/diagnostico-de-dengue-e-chikungunya-em-feira-de-santana', destination: '/blog/diagnostico-de-dengue-e-chikungunya-em-feira-de-santana', permanent: true },
  { source: '/agende-o-seu-check-up-em-feira-de-santana', destination: '/blog/agende-o-seu-check-up-em-feira-de-santana', permanent: true },
  { source: '/exame-ca-15-3-em-feira-de-santana', destination: '/blog/exame-ca-15-3-em-feira-de-santana', permanent: true },
  { source: '/acidente-vascular-cerebral-avc', destination: '/blog/acidente-vascular-cerebral-avc', permanent: true },
  { source: '/faca-o-seu-teste-proteja-se-contra-o-hiv', destination: '/blog/faca-o-seu-teste-proteja-se-contra-o-hiv', permanent: true },
  { source: '/anticorpos-neutralizantes', destination: '/blog/anticorpos-neutralizantes', permanent: true },
  { source: '/sexagem-fetal-em-feira-de-santana', destination: '/blog/sexagem-fetal-em-feira-de-santana', permanent: true },
  { source: '/rt-pcr-em-feira-de-santana', destination: '/blog/rt-pcr-em-feira-de-santana', permanent: true },
  { source: '/3-alimentos-otimos-para-sua-digestao', destination: '/blog/3-alimentos-otimos-para-sua-digestao', permanent: true },
  { source: '/os-perigos-da-obsidade-infantil', destination: '/blog/os-perigos-da-obsidade-infantil', permanent: true },
  { source: '/resultados-de-laboratorios-mais-precisos-em-feira-de-santana', destination: '/blog/resultados-de-laboratorios-mais-precisos-em-feira-de-santana', permanent: true },
  { source: '/exames-laboratoriais-em-feira-de-santana', destination: '/blog/exames-laboratoriais-em-feira-de-santana', permanent: true },
  { source: '/qual-a-diferenca-entre-hdl-vs-ldl', destination: '/blog/qual-a-diferenca-entre-hdl-vs-ldl', permanent: true },
  // NOTA: URLs com ?p= não podem ser redirecionadas dessa forma no Next.js
  // { source: '/?p=3786', destination: '/blog/?p=3786', permanent: true },
  { source: '/dia-do-abraco', destination: '/blog/dia-do-abraco', permanent: true },
  { source: '/se-hidrate-consumindo-frutas', destination: '/blog/se-hidrate-consumindo-frutas', permanent: true },
  { source: '/quando-devo-fazer-um-check-up', destination: '/blog/quando-devo-fazer-um-check-up', permanent: true },
  { source: '/autoexame-da-tireoide', destination: '/blog/autoexame-da-tireoide', permanent: true },
  { source: '/6-6-dia-nacional-do-teste-do-pezinho', destination: '/blog/6-6-dia-nacional-do-teste-do-pezinho', permanent: true },
  { source: '/exame-3-em-1', destination: '/blog/exame-3-em-1', permanent: true },
  { source: '/sintomas-de-covid', destination: '/blog/sintomas-de-covid', permanent: true },
  { source: '/beta-hcg', destination: '/blog/beta-hcg', permanent: true },
  { source: '/resultado-online', destination: '/blog/resultado-online', permanent: true },
  { source: '/descubra-se-esta-com-covid-de-forma-rapida', destination: '/blog/descubra-se-esta-com-covid-de-forma-rapida', permanent: true },
  { source: '/fique-por-dentro', destination: '/blog/fique-por-dentro', permanent: true },
  { source: '/julho-amarelo', destination: '/blog/julho-amarelo', permanent: true },
  { source: '/anacli-agora-esta-no-hospital-regional', destination: '/blog/anacli-agora-esta-no-hospital-regional', permanent: true },
  { source: '/curiosidades', destination: '/blog/curiosidades', permanent: true },
  { source: '/1o-de-agosto-dia-mundial-da-amamentacao', destination: '/blog/1o-de-agosto-dia-mundial-da-amamentacao', permanent: true },
  { source: '/certificado-de-acreditacao-da-anacli', destination: '/blog/certificado-de-acreditacao-da-anacli', permanent: true },
  { source: '/dia-05-08-nacional-da-saude', destination: '/blog/dia-05-08-nacional-da-saude', permanent: true },
  { source: '/curiosidades-2', destination: '/blog/curiosidades-2', permanent: true },
  { source: '/8-de-agosto-dia-de-nacional-combate-ao-colesterol', destination: '/blog/8-de-agosto-dia-de-nacional-combate-ao-colesterol', permanent: true },
  { source: '/3938-2', destination: '/blog/3938-2', permanent: true },
  { source: '/alimentos-ricos-em-vitamina-c', destination: '/blog/alimentos-ricos-em-vitamina-c', permanent: true },
  { source: '/beneficios-do-leite-materno', destination: '/blog/beneficios-do-leite-materno', permanent: true },
  { source: '/atendimento-movel-em-feira-de-santana', destination: '/blog/atendimento-movel-em-feira-de-santana', permanent: true },
  { source: '/com-a-anacli-e-tudo-mais-facil', destination: '/blog/com-a-anacli-e-tudo-mais-facil', permanent: true },
  { source: '/14-de-agosto-dia-do-cardiologista', destination: '/blog/14-de-agosto-dia-do-cardiologista', permanent: true },
  { source: '/no-anacli-voce-agenda-seus-exames-com-antecedencia', destination: '/blog/no-anacli-voce-agenda-seus-exames-com-antecedencia', permanent: true },
  { source: '/exame-toxicologico-com-unidade-exclusiva-em-feira-de-santana', destination: '/blog/exame-toxicologico-com-unidade-exclusiva-em-feira-de-santana', permanent: true },
  { source: '/todos-os-caminhos-te-levao-ao-anacli', destination: '/blog/todos-os-caminhos-te-levao-ao-anacli', permanent: true },
  { source: '/excelencia-no-atendimentoum-diferencial-do-anacli', destination: '/blog/excelencia-no-atendimentoum-diferencial-do-anacli', permanent: true },
  { source: '/setembro-amarelo', destination: '/blog/setembro-amarelo', permanent: true },
  { source: '/12-09-dia-do-urologista', destination: '/blog/12-09-dia-do-urologista', permanent: true },
  { source: '/setembro-um-mes-para-valorizar-a-vida', destination: '/blog/setembro-um-mes-para-valorizar-a-vida', permanent: true },
  { source: '/21-09-dia-mundial-da-doenca-de-alzheimer', destination: '/blog/21-09-dia-mundial-da-doenca-de-alzheimer', permanent: true },
  { source: '/cuide-da-sua-saude', destination: '/blog/cuide-da-sua-saude', permanent: true },
  { source: '/16-09-dia-nacional-de-combate-e-prevecao-a-trombose', destination: '/blog/16-09-dia-nacional-de-combate-e-prevecao-a-trombose', permanent: true },
  { source: '/a-importancia-da-alimentacao-saudavel-na-gestacao', destination: '/blog/a-importancia-da-alimentacao-saudavel-na-gestacao', permanent: true },
  { source: '/exame-toxicologico-em-feira-de-santana', destination: '/blog/exame-toxicologico-em-feira-de-santana', permanent: true },
  { source: '/outubro-rosa', destination: '/blog/outubro-rosa', permanent: true },
  { source: '/curiosidades-3', destination: '/blog/curiosidades-3', permanent: true },
  { source: '/17-10-dia-mundia-da-hipertensao', destination: '/blog/17-10-dia-mundia-da-hipertensao', permanent: true },
  { source: '/18-de-outubro-dia-do-medico', destination: '/blog/18-de-outubro-dia-do-medico', permanent: true },
  { source: '/19-10-dia-nacional-de-combate-a-sifiles-e-a-sifiles-congenita', destination: '/blog/19-10-dia-nacional-de-combate-a-sifiles-e-a-sifiles-congenita', permanent: true },
  { source: '/exames-toxicologicos-em-feira-de-santana', destination: '/blog/exames-toxicologicos-em-feira-de-santana', permanent: true },
  { source: '/bebidas-alcoolicas-afetam-os-resultados-dos-exames', destination: '/blog/bebidas-alcoolicas-afetam-os-resultados-dos-exames', permanent: true },
  { source: '/teste-do-pezinho-em-feira-de-santana', destination: '/blog/teste-do-pezinho-em-feira-de-santana', permanent: true },
  { source: '/parabens-servidor-publico', destination: '/blog/parabens-servidor-publico', permanent: true },
  { source: '/5-exames-importantes-para-monitorar-a-diabetes', destination: '/blog/5-exames-importantes-para-monitorar-a-diabetes', permanent: true },
  { source: '/hepatites-virais', destination: '/blog/hepatites-virais', permanent: true },
  { source: '/certificado-excelencia-laboratorial', destination: '/blog/certificado-excelencia-laboratorial', permanent: true },
  { source: '/17-11-dia-mundial-de-combate-ao-cancer-de-prostata', destination: '/blog/17-11-dia-mundial-de-combate-ao-cancer-de-prostata', permanent: true },
  { source: '/check-up-infantil-em-feira-de-santana', destination: '/blog/check-up-infantil-em-feira-de-santana', permanent: true },
  { source: '/20-11-dia-do-biomedico', destination: '/blog/20-11-dia-do-biomedico', permanent: true },
  { source: '/20-11-dia-da-consciencia-negra', destination: '/blog/20-11-dia-da-consciencia-negra', permanent: true },
  { source: '/anacli-kids-2', destination: '/blog/anacli-kids-2', permanent: true },
  { source: '/27-11-dia-nacional-da-luta-contra-o-cancer-de-mama', destination: '/blog/27-11-dia-nacional-da-luta-contra-o-cancer-de-mama', permanent: true },
  { source: '/anacli-atendimento-e-estrutura-de-excelencia', destination: '/blog/anacli-atendimento-e-estrutura-de-excelencia', permanent: true },
  { source: '/todo-dia-e-dia-de-se-cuidar', destination: '/blog/todo-dia-e-dia-de-se-cuidar', permanent: true },
  { source: '/curiosidades-4', destination: '/blog/curiosidades-4', permanent: true },
  { source: '/a-importancia-de-fazer-exames-laboratoriais-de-rotina', destination: '/blog/a-importancia-de-fazer-exames-laboratoriais-de-rotina', permanent: true },
  { source: '/dezembro-laranja-e-vermelho-a-conscientizacao-no-combate-a-desinformacao-e-ao-preconceito', destination: '/blog/dezembro-laranja-e-vermelho-a-conscientizacao-no-combate-a-desinformacao-e-ao-preconceito', permanent: true },
  { source: '/feliz-natal', destination: '/blog/feliz-natal', permanent: true },
  { source: '/sintomas-de-gripe', destination: '/blog/sintomas-de-gripe', permanent: true },
  { source: '/quais-os-riscos-de-ficar-sentado-por-muito-tempo', destination: '/blog/quais-os-riscos-de-ficar-sentado-por-muito-tempo', permanent: true },
  { source: '/anacli-laboratorio-certificado', destination: '/blog/anacli-laboratorio-certificado', permanent: true },
  { source: '/qual-a-importancia-da-panturrilha', destination: '/blog/qual-a-importancia-da-panturrilha', permanent: true },
  { source: '/qual-a-importancia-de-realizar-o-exame-check-up-infantil', destination: '/blog/qual-a-importancia-de-realizar-o-exame-check-up-infantil', permanent: true },
  { source: '/a-importancia-da-vitamina-d-para-o-organismo', destination: '/blog/a-importancia-da-vitamina-d-para-o-organismo', permanent: true },
  { source: '/qual-tempo-de-validade-dos-exames', destination: '/blog/qual-tempo-de-validade-dos-exames', permanent: true },
  { source: '/intolerancia-a-lactose-quais-os-sintomas-e-como-lidar', destination: '/blog/intolerancia-a-lactose-quais-os-sintomas-e-como-lidar', permanent: true },
  { source: '/por-que-fazer-check-up-regularmente', destination: '/blog/por-que-fazer-check-up-regularmente', permanent: true },
  { source: '/priorize-a-saude-da-sua-gestacao', destination: '/blog/priorize-a-saude-da-sua-gestacao', permanent: true },
  { source: '/glicemia-a-importancia-do-controle-glicemico', destination: '/blog/glicemia-a-importancia-do-controle-glicemico', permanent: true },
  { source: '/anacli-conquista-certificacao-iso-9001-pela-excelencia-no-atendimento', destination: '/blog/anacli-conquista-certificacao-iso-9001-pela-excelencia-no-atendimento', permanent: true },
  { source: '/a-sua-satisfacao-e-a-nossa-missao', destination: '/blog/a-sua-satisfacao-e-a-nossa-missao', permanent: true },
  { source: '/diabetes-entenda-as-diferencas-entre-os-tipos-1-e-2', destination: '/blog/diabetes-entenda-as-diferencas-entre-os-tipos-1-e-2', permanent: true },
  { source: '/por-que-e-importante-fazer-o-exame-de-colesterol', destination: '/blog/por-que-e-importante-fazer-o-exame-de-colesterol', permanent: true },
  { source: '/quem-e-voce-na-hora-da-coleta', destination: '/blog/quem-e-voce-na-hora-da-coleta', permanent: true },
  { source: '/e-permitido-beber-agua-para-realizar-exame', destination: '/blog/e-permitido-beber-agua-para-realizar-exame', permanent: true },
  { source: '/quais-sao-os-principais-exames-laboratoriais-de-rotina', destination: '/blog/quais-sao-os-principais-exames-laboratoriais-de-rotina', permanent: true },
  { source: '/por-que-e-importante-realizar-exames-laboratorias', destination: '/blog/por-que-e-importante-realizar-exames-laboratorias', permanent: true },
  { source: '/qual-a-importancia-do-teste-do-pezinho-no-bebe', destination: '/blog/qual-a-importancia-do-teste-do-pezinho-no-bebe', permanent: true },
  { source: '/como-anda-o-seu-cortisol', destination: '/blog/como-anda-o-seu-cortisol', permanent: true },
  { source: '/como-ter-uma-rotina-saudavel-de-sono', destination: '/blog/como-ter-uma-rotina-saudavel-de-sono', permanent: true },
  { source: '/anacli-cuidado-na-comodidade-da-sua-casa', destination: '/blog/anacli-cuidado-na-comodidade-da-sua-casa', permanent: true },
  { source: '/com-qual-frequencia-devemos-fazer-exames-laboratoriais', destination: '/blog/com-qual-frequencia-devemos-fazer-exames-laboratoriais', permanent: true },
  { source: '/4-motivos-para-voce-escolher-o-anacli', destination: '/blog/4-motivos-para-voce-escolher-o-anacli', permanent: true },
  { source: '/anacli-tradicao-em-exames-laboratoriais', destination: '/blog/anacli-tradicao-em-exames-laboratoriais', permanent: true },
  { source: '/planos-que-atendem-no-anacli', destination: '/blog/planos-que-atendem-no-anacli', permanent: true },
  { source: '/quanto-tempo-vale-um-resultado-de-exame-laboratorial', destination: '/blog/quanto-tempo-vale-um-resultado-de-exame-laboratorial', permanent: true },
  { source: '/sexagem-fetal-quando-devo-realizar-o-exame', destination: '/blog/sexagem-fetal-quando-devo-realizar-o-exame', permanent: true },
  { source: '/qual-o-seu-conceito-de-saude', destination: '/blog/qual-o-seu-conceito-de-saude', permanent: true },
  { source: '/saiba-o-que-nao-fazer-apos-coleta-de-sangue', destination: '/blog/saiba-o-que-nao-fazer-apos-coleta-de-sangue', permanent: true },
  { source: '/entenda-a-importancia-de-cuidar-da-saude-da-crianca', destination: '/blog/entenda-a-importancia-de-cuidar-da-saude-da-crianca', permanent: true },
  { source: '/comece-seu-dia-com-um-toque-de-saude-no-anacli', destination: '/blog/comece-seu-dia-com-um-toque-de-saude-no-anacli', permanent: true },
  { source: '/voce-sabe-a-diferenca-entre-alergia-e-intolerancia', destination: '/blog/voce-sabe-a-diferenca-entre-alergia-e-intolerancia', permanent: true },
  { source: '/voce-costuma-ter-boas-atitudes-para-preservar-o-meio-ambiente', destination: '/blog/voce-costuma-ter-boas-atitudes-para-preservar-o-meio-ambiente', permanent: true },
  { source: '/selos-criancas-corajosas-do-anacli', destination: '/blog/selos-criancas-corajosas-do-anacli', permanent: true },
  { source: '/dengue-transmissao-sintomas-e-tratamento', destination: '/blog/dengue-transmissao-sintomas-e-tratamento', permanent: true },
  { source: '/anacli-celebra-a-iso-9001', destination: '/blog/anacli-celebra-a-iso-9001', permanent: true },
  { source: '/cuidar-bem-de-voce-e-a-nossa-prioridade', destination: '/blog/cuidar-bem-de-voce-e-a-nossa-prioridade', permanent: true },
  { source: '/conheca-o-servico-de-coleta-domiciliar-do-anacli', destination: '/blog/conheca-o-servico-de-coleta-domiciliar-do-anacli', permanent: true },
  { source: '/problemas-respiratorios-no-inverno', destination: '/blog/problemas-respiratorios-no-inverno', permanent: true },
  { source: '/4742-2', destination: '/blog/4742-2', permanent: true },
  { source: '/voce-ja-fez-o-check-up-do-seu-filho-esse-ano', destination: '/blog/voce-ja-fez-o-check-up-do-seu-filho-esse-ano', permanent: true },
  { source: '/agende-seus-exames-online-de-forma-pratica', destination: '/blog/agende-seus-exames-online-de-forma-pratica', permanent: true },
  { source: '/hepatites-virais-conheca-os-exames-que-podem-ajudar-no-diagnostico', destination: '/blog/hepatites-virais-conheca-os-exames-que-podem-ajudar-no-diagnostico', permanent: true },
  { source: '/tireoide-fique-atento-aos-sinais', destination: '/blog/tireoide-fique-atento-aos-sinais', permanent: true },
  { source: '/entenda-a-importancia-do-exame-psa', destination: '/blog/entenda-a-importancia-do-exame-psa', permanent: true },
  { source: '/precisao-e-rapidez-em-resultados-e-no-anacli', destination: '/blog/precisao-e-rapidez-em-resultados-e-no-anacli', permanent: true },
  { source: '/anacli-celebra-o-dia-do-psicologo', destination: '/blog/anacli-celebra-o-dia-do-psicologo', permanent: true },
  { source: '/priorize-a-saude-da-sua-gestacao-2', destination: '/blog/priorize-a-saude-da-sua-gestacao-2', permanent: true },
  { source: '/fique-atento', destination: '/blog/fique-atento', permanent: true },
  { source: '/prevencao-e-controle-do-colesterol', destination: '/blog/prevencao-e-controle-do-colesterol', permanent: true },
  { source: '/anacli-conforto-e-agilidade-na-realizacao-dos-exames', destination: '/blog/anacli-conforto-e-agilidade-na-realizacao-dos-exames', permanent: true },
  { source: '/setembro-amarelo-sua-vida-importa', destination: '/blog/setembro-amarelo-sua-vida-importa', permanent: true },
  { source: '/certificado-de-coragem-anacli', destination: '/blog/certificado-de-coragem-anacli', permanent: true },
  { source: '/anacli-o-melhor-em-ambientacao-e-conforto', destination: '/blog/anacli-o-melhor-em-ambientacao-e-conforto', permanent: true },
  { source: '/check-up-masculino-quais-exames-todo-homem-deve-fazer', destination: '/blog/check-up-masculino-quais-exames-todo-homem-deve-fazer', permanent: true },
  { source: '/cuidados-no-verao-como-se-cuidar-e-ficar-mais-seguro-nessa-epoca', destination: '/blog/cuidados-no-verao-como-se-cuidar-e-ficar-mais-seguro-nessa-epoca', permanent: true },
  { source: '/dicas-para-enfrentar-o-calor', destination: '/blog/dicas-para-enfrentar-o-calor', permanent: true },
  { source: '/3-10-dia-do-dentista', destination: '/blog/3-10-dia-do-dentista', permanent: true },
  { source: '/outubro-rosa-abrace-esta-causa', destination: '/blog/outubro-rosa-abrace-esta-causa', permanent: true },
  { source: '/mamografia-entenda-como-funciona', destination: '/blog/mamografia-entenda-como-funciona', permanent: true },
  { source: '/sua-saude-e-a-nossa-prioridade-sempre', destination: '/blog/sua-saude-e-a-nossa-prioridade-sempre', permanent: true },
  { source: '/todo-dia-e-dia-de-cuidar-da-sua-saude', destination: '/blog/todo-dia-e-dia-de-cuidar-da-sua-saude', permanent: true },
  { source: '/nutricionista-reforca-a-importancia-da-alimentacao-saudavel', destination: '/blog/nutricionista-reforca-a-importancia-da-alimentacao-saudavel', permanent: true },
  { source: '/anacli-excelencia-desde-ambiente-a-resultados', destination: '/blog/anacli-excelencia-desde-ambiente-a-resultados', permanent: true },
  { source: '/anacli-vai-muito-alem-de-coletas', destination: '/blog/anacli-vai-muito-alem-de-coletas', permanent: true },
  { source: '/anacli-entra-na-trend-do-momento', destination: '/blog/anacli-entra-na-trend-do-momento', permanent: true },
  { source: '/novembro-azul-junte-se-a-luta-contra-o-cancer-de-prostata', destination: '/blog/novembro-azul-junte-se-a-luta-contra-o-cancer-de-prostata', permanent: true },
  { source: '/novembro-azul-homem-de-atitude-se-cuida', destination: '/blog/novembro-azul-homem-de-atitude-se-cuida', permanent: true },
  { source: '/entenda-a-importancia-do-novembro-azul', destination: '/blog/entenda-a-importancia-do-novembro-azul', permanent: true },
  { source: '/dia-mundial-do-diabetes-a-importancia-da-conscientizacao', destination: '/blog/dia-mundial-do-diabetes-a-importancia-da-conscientizacao', permanent: true },
  { source: '/dia-do-biomedico-conheca-a-importancia-da-profissao', destination: '/blog/dia-do-biomedico-conheca-a-importancia-da-profissao', permanent: true },
  { source: '/dia-nacionald-do-doador-de-sangue-faca-parte-dessa-corrente-do-bem', destination: '/blog/dia-nacionald-do-doador-de-sangue-faca-parte-dessa-corrente-do-bem', permanent: true },
  { source: '/sbe-como-funcionam-as-analises-laboratoriais', destination: '/blog/sbe-como-funcionam-as-analises-laboratoriais', permanent: true },
  { source: '/cuidar-da-saude-nao-tem-idade', destination: '/blog/cuidar-da-saude-nao-tem-idade', permanent: true },
  { source: '/anacli-fazendo-parte-de-vidas-que-ainda-nem-sairam-da-barriga-da-mamae', destination: '/blog/anacli-fazendo-parte-de-vidas-que-ainda-nem-sairam-da-barriga-da-mamae', permanent: true },
  { source: '/a-importancia-da-vitamina-d-para-o-organismo-2', destination: '/blog/a-importancia-da-vitamina-d-para-o-organismo-2', permanent: true },
  { source: '/exame-anti-mulleriano-o-que-e-e-como-funciona', destination: '/blog/exame-anti-mulleriano-o-que-e-e-como-funciona', permanent: true },
  { source: '/a-importancia-da-prevencao-na-saude-infantil', destination: '/blog/a-importancia-da-prevencao-na-saude-infantil', permanent: true },
  { source: '/eficiencia-nos-exames-salva-vidas', destination: '/blog/eficiencia-nos-exames-salva-vidas', permanent: true },
  { source: '/doencas-silenciosas-saiba-quais-sao-e-como-identificar', destination: '/blog/doencas-silenciosas-saiba-quais-sao-e-como-identificar', permanent: true },
  { source: '/anacli-recebe-certificado-de-excelencia', destination: '/blog/anacli-recebe-certificado-de-excelencia', permanent: true },
  { source: '/voce-sabe-como-funciona-os-exames-toxicologicos', destination: '/blog/voce-sabe-como-funciona-os-exames-toxicologicos', permanent: true },
  { source: '/dezembro-laranja-mes-de-conscientizacao-do-cancer-de-pele', destination: '/blog/dezembro-laranja-mes-de-conscientizacao-do-cancer-de-pele', permanent: true },
  { source: '/resultados-na-palma-da-sua-mao', destination: '/blog/resultados-na-palma-da-sua-mao', permanent: true },
  { source: '/principais-exames-de-rotina-para-criancas', destination: '/blog/principais-exames-de-rotina-para-criancas', permanent: true },
  { source: '/faca-ja-seu-exame-toxicologico', destination: '/blog/faca-ja-seu-exame-toxicologico', permanent: true },
  { source: '/feliz-natal-2', destination: '/blog/feliz-natal-2', permanent: true },
  { source: '/alzheimer-exame-de-sangue-que-detecta-a-doenca', destination: '/blog/alzheimer-exame-de-sangue-que-detecta-a-doenca', permanent: true },
  { source: '/4-frutas-para-consumir-durante-o-verao-e-se-refrescar', destination: '/blog/4-frutas-para-consumir-durante-o-verao-e-se-refrescar', permanent: true },
  { source: '/e-verao-aproveite-cuide-se-e-divirta-se', destination: '/blog/e-verao-aproveite-cuide-se-e-divirta-se', permanent: true },
  { source: '/prorrogado-prazo-para-realizacao-do-exame-toxicologico', destination: '/blog/prorrogado-prazo-para-realizacao-do-exame-toxicologico', permanent: true },
  { source: '/anacli-excelencia-no-atendimento-e-profissionais-capacitados', destination: '/blog/anacli-excelencia-no-atendimento-e-profissionais-capacitados', permanent: true },
  { source: '/anacli-experiencia-especializada-na-coleta-infantil', destination: '/blog/anacli-experiencia-especializada-na-coleta-infantil', permanent: true },
  { source: '/exames-de-sangue-de-rotina-com-que-frequencia-devo-fazer', destination: '/blog/exames-de-sangue-de-rotina-com-que-frequencia-devo-fazer', permanent: true },
  { source: '/que-tal-iniciar-o-ano-cuidando-da-sua-saude', destination: '/blog/que-tal-iniciar-o-ano-cuidando-da-sua-saude', permanent: true },
  { source: '/prazos-para-exame-toxicologico-periodo-foi-prorrogado', destination: '/blog/prazos-para-exame-toxicologico-periodo-foi-prorrogado', permanent: true },
  { source: '/casos-de-dengue-em-2024-triplicam-em-relacao-ao-inicio-de-2023', destination: '/blog/casos-de-dengue-em-2024-triplicam-em-relacao-ao-inicio-de-2023', permanent: true },
  { source: '/4-dicas-para-curtir-o-carnaval-com-mais-saude-e-seguranca', destination: '/blog/4-dicas-para-curtir-o-carnaval-com-mais-saude-e-seguranca', permanent: true },
  { source: '/mais-um-dia-de-coletas-e-analises-no-anacli', destination: '/blog/mais-um-dia-de-coletas-e-analises-no-anacli', permanent: true },
  { source: '/exercicio-saude-e-verao-o-equilibrio-essencial-na-estacao-mais-quente-do-ano', destination: '/blog/exercicio-saude-e-verao-o-equilibrio-essencial-na-estacao-mais-quente-do-ano', permanent: true },
  { source: '/sumario-de-urina-como-funciona', destination: '/blog/sumario-de-urina-como-funciona', permanent: true },
  { source: '/principais-exames-que-a-gestante-deve-fazer', destination: '/blog/principais-exames-que-a-gestante-deve-fazer', permanent: true },
  { source: '/exames-e-cuidados-essenciais-para-a-saude-dos-idosos', destination: '/blog/exames-e-cuidados-essenciais-para-a-saude-dos-idosos', permanent: true },
  { source: '/beber-agua-quebra-o-jejum', destination: '/blog/beber-agua-quebra-o-jejum', permanent: true },
  { source: '/jogo-do-autocuidado-estrategias-para-uma-vida-equilibrada-e-plena', destination: '/blog/jogo-do-autocuidado-estrategias-para-uma-vida-equilibrada-e-plena', permanent: true },
  { source: '/anacli-recebe-certificado-de-conformidade-elevando-padroes-de-qualidade', destination: '/blog/anacli-recebe-certificado-de-conformidade-elevando-padroes-de-qualidade', permanent: true },
  { source: '/como-anda-sua-saude-pos-carnaval', destination: '/blog/como-anda-sua-saude-pos-carnaval', permanent: true },
  { source: '/quem-por-aqui-esta-devendo-o-exame-toxicologico', destination: '/blog/quem-por-aqui-esta-devendo-o-exame-toxicologico', permanent: true },
  { source: '/alerta-vermelho-casos-de-dengue-explodem-no-brasil', destination: '/blog/alerta-vermelho-casos-de-dengue-explodem-no-brasil', permanent: true },
  { source: '/o-papel-do-colesterol-hdl-e-ldl-na-saude-cardiovascular', destination: '/blog/o-papel-do-colesterol-hdl-e-ldl-na-saude-cardiovascular', permanent: true },
  { source: '/a-importancia-da-coleta-de-sangue-em-criancas', destination: '/blog/a-importancia-da-coleta-de-sangue-em-criancas', permanent: true },
  { source: '/obesidade-nao-e-sobre-medidas-e-sobre-saude', destination: '/blog/obesidade-nao-e-sobre-medidas-e-sobre-saude', permanent: true },
  { source: '/dengue-zika-e-chikungunya-como-idetificar', destination: '/blog/dengue-zika-e-chikungunya-como-idetificar', permanent: true },
  { source: '/agua-nosso-bem-mais-precioso', destination: '/blog/agua-nosso-bem-mais-precioso', permanent: true },
  { source: '/anacli-parceiro-de-confianca-no-cuidado-da-saude', destination: '/blog/anacli-parceiro-de-confianca-no-cuidado-da-saude', permanent: true },
  { source: '/exames-de-rotina-para-gestantes-gravidez-saudavel-e-tranquila', destination: '/blog/exames-de-rotina-para-gestantes-gravidez-saudavel-e-tranquila', permanent: true },
  { source: '/agende-seus-exames-no-anacli', destination: '/blog/agende-seus-exames-no-anacli', permanent: true },
  { source: '/5-motivos-para-escolher-o-anacli', destination: '/blog/5-motivos-para-escolher-o-anacli', permanent: true },
  { source: '/dia-mundial-de-conscientizacao-do-autismo-juntos-pela-inclusao-e-compreensao', destination: '/blog/dia-mundial-de-conscientizacao-do-autismo-juntos-pela-inclusao-e-compreensao', permanent: true },
  { source: '/dia-mundial-da-saude-priorizando-o-bem-estar-global', destination: '/blog/dia-mundial-da-saude-priorizando-o-bem-estar-global', permanent: true },
  { source: '/nao-caia-em-fake-news', destination: '/blog/nao-caia-em-fake-news', permanent: true },
  { source: '/anacli-excelencia-em-cada-interacao', destination: '/blog/anacli-excelencia-em-cada-interacao', permanent: true },
  { source: '/tipos-de-pacientes-na-hora-da-coleta-de-sangue-entendenda-as-reacoes', destination: '/blog/tipos-de-pacientes-na-hora-da-coleta-de-sangue-entendenda-as-reacoes', permanent: true },
  { source: '/cuidado-a-dengue-esta-batendo-a-nossa-porta-com-forca-renovada', destination: '/blog/cuidado-a-dengue-esta-batendo-a-nossa-porta-com-forca-renovada', permanent: true },
  { source: '/os-perigos-da-automedicacao', destination: '/blog/os-perigos-da-automedicacao', permanent: true },
  { source: '/a-importancia-da-hidratacao-para-a-saude', destination: '/blog/a-importancia-da-hidratacao-para-a-saude', permanent: true },
  { source: '/motoristas-sem-exame-toxicologico-serao-notificados', destination: '/blog/motoristas-sem-exame-toxicologico-serao-notificados', permanent: true },
  { source: '/sera-que-um-simples-cha-quebra-o-jejum-antes-de-um-exame-de-sangue', destination: '/blog/sera-que-um-simples-cha-quebra-o-jejum-antes-de-um-exame-de-sangue', permanent: true },
  { source: '/certificado-de-coragem-para-os-super-corajosos', destination: '/blog/certificado-de-coragem-para-os-super-corajosos', permanent: true },
  { source: '/seus-exames-com-mais-praticidade-e-rapidez-no-laboratorio-anacli', destination: '/blog/seus-exames-com-mais-praticidade-e-rapidez-no-laboratorio-anacli', permanent: true },
  { source: '/anacli-precisao-e-confiabilidade', destination: '/blog/anacli-precisao-e-confiabilidade', permanent: true },
  { source: '/dia-das-maes-celebrando-o-amor-que-nunca-acaba', destination: '/blog/dia-das-maes-celebrando-o-amor-que-nunca-acaba', permanent: true },
  { source: '/valorize-sua-saude-e-sua-seguranca-nas-estradas', destination: '/blog/valorize-sua-saude-e-sua-seguranca-nas-estradas', permanent: true },
  { source: '/cuidar-da-saude-da-familia-e-demonstrar-amor', destination: '/blog/cuidar-da-saude-da-familia-e-demonstrar-amor', permanent: true },
  { source: '/beta-hcg-como-era-o-primeiro-laudo-ha-60-anos-no-anacli', destination: '/blog/beta-hcg-como-era-o-primeiro-laudo-ha-60-anos-no-anacli', permanent: true },
  { source: '/anacli-conquista-certificado-de-qualidade-internacional-prevecal', destination: '/blog/anacli-conquista-certificado-de-qualidade-internacional-prevecal', permanent: true },
  { source: '/anacli-e-certificado-com-qualidade-nacional', destination: '/blog/anacli-e-certificado-com-qualidade-nacional', permanent: true },
  { source: '/voce-ja-ouviu-falar-sobre-sexagem-fetal', destination: '/blog/voce-ja-ouviu-falar-sobre-sexagem-fetal', permanent: true },
  { source: '/anacli-cuidado-e-dedicacao-com-os-pequenos', destination: '/blog/anacli-cuidado-e-dedicacao-com-os-pequenos', permanent: true },
  { source: '/febre-oropouche-diagnostico-disponivel-no-laboratorio-anacli', destination: '/blog/febre-oropouche-diagnostico-disponivel-no-laboratorio-anacli', permanent: true },
  { source: '/teste-do-pezinho-essencial-para-a-saude-dos-recem-nascidos', destination: '/blog/teste-do-pezinho-essencial-para-a-saude-dos-recem-nascidos', permanent: true },
  { source: '/vacinas-um-escudo-vital-contra-doencas', destination: '/blog/vacinas-um-escudo-vital-contra-doencas', permanent: true },
  { source: '/precaucoes-importantes-ao-realizar-coletas-de-exames-de-sangue', destination: '/blog/precaucoes-importantes-ao-realizar-coletas-de-exames-de-sangue', permanent: true },
  { source: '/anacli-marca-presenca-no-49o-congresso-brasileiro-de-analises-clinicas-cbac', destination: '/blog/anacli-marca-presenca-no-49o-congresso-brasileiro-de-analises-clinicas-cbac', permanent: true },
  { source: '/entenda-a-febre-oropouche-sintomas-recorrencia-e-complicacoes', destination: '/blog/entenda-a-febre-oropouche-sintomas-recorrencia-e-complicacoes', permanent: true },
  { source: '/qual-e-a-emocao-no-controle-da-sua-mente-na-hora-da-coleta', destination: '/blog/qual-e-a-emocao-no-controle-da-sua-mente-na-hora-da-coleta', permanent: true },
  { source: '/a-importancia-da-vacina-bcg-na-protecao-dos-recem-nascidos', destination: '/blog/a-importancia-da-vacina-bcg-na-protecao-dos-recem-nascidos', permanent: true },
  { source: '/conheca-a-importancia-de-saber-seu-tipo-sanguineo', destination: '/blog/conheca-a-importancia-de-saber-seu-tipo-sanguineo', permanent: true },
  { source: '/anacli-acreditacao-renovada-e-compromisso-com-a-excelencia', destination: '/blog/anacli-acreditacao-renovada-e-compromisso-com-a-excelencia', permanent: true },
  { source: '/como-se-proteger-das-doencas-do-inverno-gripe-resfriado-e-bronquite', destination: '/blog/como-se-proteger-das-doencas-do-inverno-gripe-resfriado-e-bronquite', permanent: true },
  { source: '/por-que-e-importante-fazer-o-teste-da-gripe', destination: '/blog/por-que-e-importante-fazer-o-teste-da-gripe', permanent: true },
  { source: '/5-dicas-para-cuidar-da-saude-no-inverno', destination: '/blog/5-dicas-para-cuidar-da-saude-no-inverno', permanent: true },
  { source: '/seus-exames-estao-em-dia-a-importancia-dos-exames-de-rotina', destination: '/blog/seus-exames-estao-em-dia-a-importancia-dos-exames-de-rotina', permanent: true },
  { source: '/ja-fez-seu-exame-de-colesterol-este-ano', destination: '/blog/ja-fez-seu-exame-de-colesterol-este-ano', permanent: true },
  { source: '/cuidar-de-voce-e-a-nossa-prioridade', destination: '/blog/cuidar-de-voce-e-a-nossa-prioridade', permanent: true },
  { source: '/saiba-como-descobrir-qual-hormonio-esta-dominando-seu-dia', destination: '/blog/saiba-como-descobrir-qual-hormonio-esta-dominando-seu-dia', permanent: true },
  { source: '/incompatibilidade-sanguinea-quais-os-riscos-e-a-importancia-do-diagnostico', destination: '/blog/incompatibilidade-sanguinea-quais-os-riscos-e-a-importancia-do-diagnostico', permanent: true },
  { source: '/dia-nacional-da-saude-mudanca-de-habitos-para-uma-vida-saudavel', destination: '/blog/dia-nacional-da-saude-mudanca-de-habitos-para-uma-vida-saudavel', permanent: true },
  { source: '/anacli-recebe-visita-ilustre-da-lutadora-de-ufc-virna-jandiroba', destination: '/blog/anacli-recebe-visita-ilustre-da-lutadora-de-ufc-virna-jandiroba', permanent: true },
  { source: '/laboratorio-anacli-compromisso-com-a-sua-saude', destination: '/blog/laboratorio-anacli-compromisso-com-a-sua-saude', permanent: true },
  { source: '/dia-do-cardiologista-celebrando-os-guardioes-do-coracao', destination: '/blog/dia-do-cardiologista-celebrando-os-guardioes-do-coracao', permanent: true },
  { source: '/dia-do-nutricionista-conheca-o-papel-essencial-desses-profissionais-da-saude', destination: '/blog/dia-do-nutricionista-conheca-o-papel-essencial-desses-profissionais-da-saude', permanent: true },
  { source: '/a-importancia-de-adotar-habitos-saudaveis-desde-cedo', destination: '/blog/a-importancia-de-adotar-habitos-saudaveis-desde-cedo', permanent: true },
  { source: '/uso-de-medicamentos-a-importancia-de-informar-ao-laboratorio', destination: '/blog/uso-de-medicamentos-a-importancia-de-informar-ao-laboratorio', permanent: true },
  { source: '/dia-do-endocrinologista-reconhecimento-e-dedicacao-a-saude-hormonal', destination: '/blog/dia-do-endocrinologista-reconhecimento-e-dedicacao-a-saude-hormonal', permanent: true },
  { source: '/como-saber-se-voce-esta-com-anemia', destination: '/blog/como-saber-se-voce-esta-com-anemia', permanent: true },
  { source: '/dia-nacional-de-combate-e-prevencao-a-trombose-um-alerta-para-a-saude-vascular', destination: '/blog/dia-nacional-de-combate-e-prevencao-a-trombose-um-alerta-para-a-saude-vascular', permanent: true },
  { source: '/setembro-mes-do-coracao-e-a-importancia-do-cuidado-cardiovascular', destination: '/blog/setembro-mes-do-coracao-e-a-importancia-do-cuidado-cardiovascular', permanent: true },
  { source: '/dia-nacional-de-luta-da-pessoa-com-deficiencia-conscientizacao-inclusao-e-igualdade', destination: '/blog/dia-nacional-de-luta-da-pessoa-com-deficiencia-conscientizacao-inclusao-e-igualdade', permanent: true },
  { source: '/dia-mundial-do-coracao-a-importancia-de-cuidar-do-seu-coracao-todos-os-dias', destination: '/blog/dia-mundial-do-coracao-a-importancia-de-cuidar-do-seu-coracao-todos-os-dias', permanent: true },
  { source: '/anacli-cuidando-da-sua-saude-com-parcerias-de-confianca', destination: '/blog/anacli-cuidando-da-sua-saude-com-parcerias-de-confianca', permanent: true },
  { source: '/setembro-amarelo-a-importancia-da-ccnscientizacao-sobre-a-saude-mental', destination: '/blog/setembro-amarelo-a-importancia-da-ccnscientizacao-sobre-a-saude-mental', permanent: true },
  { source: '/como-a-atividade-fisica-pode-interferir-nos-resultados-dos-exames', destination: '/blog/como-a-atividade-fisica-pode-interferir-nos-resultados-dos-exames', permanent: true },
  { source: '/exames-essenciais-para-un-check-up-completo', destination: '/blog/exames-essenciais-para-un-check-up-completo', permanent: true },
  { source: '/a-importancia-do-check-up-infantil', destination: '/blog/a-importancia-do-check-up-infantil', permanent: true },
  { source: '/cortisol-como-controlar-o-hormonio-do-estresse-e-proteger-sua-saude', destination: '/blog/cortisol-como-controlar-o-hormonio-do-estresse-e-proteger-sua-saude', permanent: true },
  { source: '/dia-mundial-da-saude-mental-a-importancia-do-cuidado-com-a-mente', destination: '/blog/dia-mundial-da-saude-mental-a-importancia-do-cuidado-com-a-mente', permanent: true },
  { source: '/por-que-descartar-o-primeiro-jato-de-urina-e-essencial-no-exame', destination: '/blog/por-que-descartar-o-primeiro-jato-de-urina-e-essencial-no-exame', permanent: true },
  { source: '/a-importancia-dos-exames-laboratoriais-no-diagnostico', destination: '/blog/a-importancia-dos-exames-laboratoriais-no-diagnostico', permanent: true },
  { source: '/outubro-rosa-o-autocuidado-e-um-ato-de-amor', destination: '/blog/outubro-rosa-o-autocuidado-e-um-ato-de-amor', permanent: true },
  { source: '/brca1-e-brca2-a-importancia-dos-testes-geneticos-para-o-tratamento-precoce-do-cancer', destination: '/blog/brca1-e-brca2-a-importancia-dos-testes-geneticos-para-o-tratamento-precoce-do-cancer', permanent: true },
  { source: '/ca-15-3-entenda-a-importancia-e-como-e-realizado', destination: '/blog/ca-15-3-entenda-a-importancia-e-como-e-realizado', permanent: true },
  { source: '/novembro-azul-prevencao-e-diagnostico-precoce-do-cancer-de-prostata', destination: '/blog/novembro-azul-prevencao-e-diagnostico-precoce-do-cancer-de-prostata', permanent: true },
  { source: '/a-importancia-do-exame-de-psa-para-a-saude-do-homem', destination: '/blog/a-importancia-do-exame-de-psa-para-a-saude-do-homem', permanent: true },
  { source: '/verdades-sobre-exames-laboratoriais-desmistificando-preocupacoes-comuns', destination: '/blog/verdades-sobre-exames-laboratoriais-desmistificando-preocupacoes-comuns', permanent: true },
  { source: '/conheca-os-novos-parceiros-do-anacli', destination: '/blog/conheca-os-novos-parceiros-do-anacli', permanent: true },
  { source: '/frutas-que-ajudam-a-controlar-a-glicose-uma-opcao-saudavel-e-saborosa', destination: '/blog/frutas-que-ajudam-a-controlar-a-glicose-uma-opcao-saudavel-e-saborosa', permanent: true },
  { source: '/dicas-para-manter-a-saude-em-dia', destination: '/blog/dicas-para-manter-a-saude-em-dia', permanent: true },
  { source: '/vai-fazer-o-psa-saiba-porque-a-abstinencia-sexual-e-fundamental', destination: '/blog/vai-fazer-o-psa-saiba-porque-a-abstinencia-sexual-e-fundamental', permanent: true },
  { source: '/tireoide-e-ganho-de-pesa-cuidados-e-prevencao', destination: '/blog/tireoide-e-ganho-de-pesa-cuidados-e-prevencao', permanent: true },
  { source: '/sinais-de-alerta-para-o-cancer-de-prostata', destination: '/blog/sinais-de-alerta-para-o-cancer-de-prostata', permanent: true },
  { source: '/vai-fazer-o-psa-saiba-porque-a-abstinencia-sexual-e-fundamental-2', destination: '/blog/vai-fazer-o-psa-saiba-porque-a-abstinencia-sexual-e-fundamental-2', permanent: true },
  { source: '/dia-mundial-do-diabetes-conscientizacao-e-prevencao-para-uma-vida-saudavel', destination: '/blog/dia-mundial-do-diabetes-conscientizacao-e-prevencao-para-uma-vida-saudavel', permanent: true },
  { source: '/dia-da-consciencia-negra-luta-resistencia-e-historia', destination: '/blog/dia-da-consciencia-negra-luta-resistencia-e-historia', permanent: true },
  { source: '/dia-do-doador-de-sangue-solidariedade-que-salva-vidas', destination: '/blog/dia-do-doador-de-sangue-solidariedade-que-salva-vidas', permanent: true },
  { source: '/dezembro-vermelho-conscientizacao-e-prevencao-contra-o-hiv-e-ists', destination: '/blog/dezembro-vermelho-conscientizacao-e-prevencao-contra-o-hiv-e-ists', permanent: true },
  { source: '/proteja-sua-pele-dos-raios-solares-nos-dias-quentes', destination: '/blog/proteja-sua-pele-dos-raios-solares-nos-dias-quentes', permanent: true },
  { source: '/cuide-da-sua-saude-antes-de-viajar-ferias-tranquilas-comecam-com-planejamento', destination: '/blog/cuide-da-sua-saude-antes-de-viajar-ferias-tranquilas-comecam-com-planejamento', permanent: true },
  { source: '/anacli-e-reconhecido-como-parceiro-oficial-do-lab-pardini', destination: '/blog/anacli-e-reconhecido-como-parceiro-oficial-do-lab-pardini', permanent: true },
  { source: '/diagnostico-do-hiv-saiba-como-identificar-a-infeccao-precocemente', destination: '/blog/diagnostico-do-hiv-saiba-como-identificar-a-infeccao-precocemente', permanent: true },
  { source: '/por-que-o-termo-mudou-de-dst-para-ist', destination: '/blog/por-que-o-termo-mudou-de-dst-para-ist', permanent: true },
  { source: '/agende-seus-exames-com-antecedencia-e-mantenha-sua-saude-em-dia', destination: '/blog/agende-seus-exames-com-antecedencia-e-mantenha-sua-saude-em-dia', permanent: true },
  { source: '/anacli-celebra-conquistas-em-2024-qualidade-compromisso-e-agradecimento-aos-nossos-pacientes', destination: '/blog/anacli-celebra-conquistas-em-2024-qualidade-compromisso-e-agradecimento-aos-nossos-pacientes', permanent: true },
  { source: '/cuidados-essenciais-com-a-saude-no-verao', destination: '/blog/cuidados-essenciais-com-a-saude-no-verao', permanent: true },
  { source: '/intolerancia-a-lactose-e-alergia-ao-leite-diferencas-e-tratamentos', destination: '/blog/intolerancia-a-lactose-e-alergia-ao-leite-diferencas-e-tratamentos', permanent: true },
  { source: '/diagnostico-de-lactose-e-alergia-ao-leite-quais-exames-fazer', destination: '/blog/diagnostico-de-lactose-e-alergia-ao-leite-quais-exames-fazer', permanent: true },
  { source: '/hormonio-anti-mulleriano-exame-que-avalia-a-reserva-ovariana', destination: '/blog/hormonio-anti-mulleriano-exame-que-avalia-a-reserva-ovariana', permanent: true },
  { source: '/anacli-celebra-recertificacao-iso-9001-pelo-3o-ano-consecutivo', destination: '/blog/anacli-celebra-recertificacao-iso-9001-pelo-3o-ano-consecutivo', permanent: true },
  { source: '/metas-para-2025-cuide-da-sua-saude-e-bem-estar', destination: '/blog/metas-para-2025-cuide-da-sua-saude-e-bem-estar', permanent: true },
  { source: '/dia-mundial-de-combate-a-hanseniase-conscientizacao-e-acao-pela-saude', destination: '/blog/dia-mundial-de-combate-a-hanseniase-conscientizacao-e-acao-pela-saude', permanent: true },
  { source: '/janeiro-roxo-mes-de-conscientizacao-e-combate-a-hanseniase', destination: '/blog/janeiro-roxo-mes-de-conscientizacao-e-combate-a-hanseniase', permanent: true },
  { source: '/o-que-um-check-up-pode-revelar-sobre-sua-saude', destination: '/blog/o-que-um-check-up-pode-revelar-sobre-sua-saude', permanent: true },
  { source: '/proteinas-exames-e-os-impactos-de-uma-dieta-rica-em-ovos', destination: '/blog/proteinas-exames-e-os-impactos-de-uma-dieta-rica-em-ovos', permanent: true },
  { source: '/exames-de-sangue-indispensaveis-para-uma-rotina-de-saude', destination: '/blog/exames-de-sangue-indispensaveis-para-uma-rotina-de-saude', permanent: true },
  { source: '/dia-mundial-contra-o-cancer-mobilizacao-pela-prevencao-e-conscientizacao', destination: '/blog/dia-mundial-contra-o-cancer-mobilizacao-pela-prevencao-e-conscientizacao', permanent: true },
  { source: '/dia-internacional-de-luta-contra-o-cancer-infantil-conscientizacao-e-apoio-as-criancas-e-familias', destination: '/blog/dia-internacional-de-luta-contra-o-cancer-infantil-conscientizacao-e-apoio-as-criancas-e-familias', permanent: true },
  { source: '/combate-ao-alcoolismo-reflexao-sobre-os-danos-a-saude-e-a-sociedade', destination: '/blog/combate-ao-alcoolismo-reflexao-sobre-os-danos-a-saude-e-a-sociedade', permanent: true },
  { source: '/cuidar-da-saude-do-corpo-essencial-para-o-bem-estar-e-longevidade', destination: '/blog/cuidar-da-saude-do-corpo-essencial-para-o-bem-estar-e-longevidade', permanent: true },
  { source: '/comece-a-malhar-com-saude-faca-exames-antes', destination: '/blog/comece-a-malhar-com-saude-faca-exames-antes', permanent: true },
  { source: '/anacli-tem-certificado-de-qualidade-internacional-prevecal', destination: '/blog/anacli-tem-certificado-de-qualidade-internacional-prevecal', permanent: true },
  { source: '/saude-e-folia-cuide-do-seu-bem-estar-no-carnaval', destination: '/blog/saude-e-folia-cuide-do-seu-bem-estar-no-carnaval', permanent: true },
  { source: '/galleri-um-avanco-na-deteccao-precoce-do-cancer', destination: '/blog/galleri-um-avanco-na-deteccao-precoce-do-cancer', permanent: true },
  { source: '/doencas-silenciosas-a-importancia-dos-exames-laboratoriais', destination: '/blog/doencas-silenciosas-a-importancia-dos-exames-laboratoriais', permanent: true },
  { source: '/pistache-um-aliado-para-seus-exames-de-sangue', destination: '/blog/pistache-um-aliado-para-seus-exames-de-sangue', permanent: true },
  { source: '/a-experiencia-no-anacli-kids-carinho-e-diversao-para-os-pequenos', destination: '/blog/a-experiencia-no-anacli-kids-carinho-e-diversao-para-os-pequenos', permanent: true },
  { source: '/doenca-celiaca-o-que-e-como-diagnosticar-e-quais-exames-sao-necessarios', destination: '/blog/doenca-celiaca-o-que-e-como-diagnosticar-e-quais-exames-sao-necessarios', permanent: true },
  { source: '/dia-internacional-da-sindrome-de-down-conscientizacao-e-inclusao', destination: '/blog/dia-internacional-da-sindrome-de-down-conscientizacao-e-inclusao', permanent: true },
  { source: '/saude-e-nutricao-pequenas-escolhas-grandes-beneficios', destination: '/blog/saude-e-nutricao-pequenas-escolhas-grandes-beneficios', permanent: true },
  { source: '/dia-mundial-de-combate-a-tuberculose-conscientizacao-e-prevencao', destination: '/blog/dia-mundial-de-combate-a-tuberculose-conscientizacao-e-prevencao', permanent: true },
  { source: '/movimente-se-pela-vida-dia-do-parkinsoniano', destination: '/blog/movimente-se-pela-vida-dia-do-parkinsoniano', permanent: true },
  { source: '/abril-azul-cada-mente-e-um-mundo-para-descobrir', destination: '/blog/abril-azul-cada-mente-e-um-mundo-para-descobrir', permanent: true },
  { source: '/anacli-saude-de-qualidade-ao-seu-alcance', destination: '/blog/anacli-saude-de-qualidade-ao-seu-alcance', permanent: true },
  { source: '/8-tipos-de-exames-laboratoriais-que-voce-nao-pode-ignorar', destination: '/blog/8-tipos-de-exames-laboratoriais-que-voce-nao-pode-ignorar', permanent: true },
  { source: '/coleta-domiciliar-comodidade-e-seguranca-no-conforto-da-sua-casa', destination: '/blog/coleta-domiciliar-comodidade-e-seguranca-no-conforto-da-sua-casa', permanent: true },
  { source: '/voce-cuida-do-seu-coracao-tanto-quanto-ele-cuida-de-voce', destination: '/blog/voce-cuida-do-seu-coracao-tanto-quanto-ele-cuida-de-voce', permanent: true },
  { source: '/descubra-o-segredo-das-cores-nos-tubos-de-coleta', destination: '/blog/descubra-o-segredo-das-cores-nos-tubos-de-coleta', permanent: true },
  { source: '/beba-agua-evite-complicacoes-de-saude', destination: '/blog/beba-agua-evite-complicacoes-de-saude', permanent: true },
  { source: '/fadiga-e-cansaco-sinais-que-seu-corpo-esta-pedindo-ajuda', destination: '/blog/fadiga-e-cansaco-sinais-que-seu-corpo-esta-pedindo-ajuda', permanent: true },
  { source: '/olhos-atentos-coracao-cuidadoso-viva-o-oftalmologista', destination: '/blog/olhos-atentos-coracao-cuidadoso-viva-o-oftalmologista', permanent: true },
  { source: '/cuidar-amar-e-proteger-un-compromisso-com-a-infancia', destination: '/blog/cuidar-amar-e-proteger-un-compromisso-com-a-infancia', permanent: true },
  { source: '/19-de-maio-um-alerta-para-o-combate-a-cefaleia', destination: '/blog/19-de-maio-um-alerta-para-o-combate-a-cefaleia', permanent: true },
  { source: '/vitamina-b12-a-causa-oculta-por-tras-do-seu-cansaco', destination: '/blog/vitamina-b12-a-causa-oculta-por-tras-do-seu-cansaco', permanent: true },
  { source: '/seu-xixi-mudou-de-cor-veja-o-que-isso-pode-indicar', destination: '/blog/seu-xixi-mudou-de-cor-veja-o-que-isso-pode-indicar', permanent: true },
  { source: '/atendimento-humanizado-mais-cuidado-mais-confianca-na-hora-do-exame', destination: '/blog/atendimento-humanizado-mais-cuidado-mais-confianca-na-hora-do-exame', permanent: true },
  { source: '/galleri-um-avanco-na-deteccao-precoce-do-cancer-2', destination: '/blog/galleri-um-avanco-na-deteccao-precoce-do-cancer-2', permanent: true },
  { source: '/habitos-que-levam-a-uma-vida-mais-duradoura-e-saudavel', destination: '/blog/habitos-que-levam-a-uma-vida-mais-duradoura-e-saudavel', permanent: true },
  { source: '/doe-sangue-salve-vidas', destination: '/blog/doe-sangue-salve-vidas', permanent: true },
  { source: '/escolha-o-caminho-mais-desafiador-habitos-saudaveis-transformam-a-vida', destination: '/blog/escolha-o-caminho-mais-desafiador-habitos-saudaveis-transformam-a-vida', permanent: true },
  { source: '/atendimento-mais-que-especial-a-essencia-humanizada-do-laboratorio-anacli', destination: '/blog/atendimento-mais-que-especial-a-essencia-humanizada-do-laboratorio-anacli', permanent: true },
  { source: '/teste-do-pezinho-exame-essencial-para-a-saude-dos-recem-nascidos', destination: '/blog/teste-do-pezinho-exame-essencial-para-a-saude-dos-recem-nascidos', permanent: true },
  { source: '/bcg-a-primeira-vacina-o-primeiro-cuidado', destination: '/blog/bcg-a-primeira-vacina-o-primeiro-cuidado', permanent: true },
  { source: '/julho-amarelo-mes-de-conscientizacao-e-combate-as-hepatites-virais', destination: '/blog/julho-amarelo-mes-de-conscientizacao-e-combate-as-hepatites-virais', permanent: true },
  { source: '/anacli-seu-laboratorio-de-confianca-na-gravidez', destination: '/blog/anacli-seu-laboratorio-de-confianca-na-gravidez', permanent: true },
  { source: '/exames-laboratoriais-de-rotina-quais-sao-e-quando-fazer', destination: '/blog/exames-laboratoriais-de-rotina-quais-sao-e-quando-fazer', permanent: true },
  { source: '/usa-mounjaro-faca-isso-antes-da-proxima-dose', destination: '/blog/usa-mounjaro-faca-isso-antes-da-proxima-dose', permanent: true },
  { source: '/seu-corpo-reage-ao-gluten-faca-os-exames-certos-com-seguranca', destination: '/blog/seu-corpo-reage-ao-gluten-faca-os-exames-certos-com-seguranca', permanent: true },
  { source: '/como-as-emocoes-influenciam-sua-saude-intestinal', destination: '/blog/como-as-emocoes-influenciam-sua-saude-intestinal', permanent: true },
  { source: '/cuidar-da-saude-desde-jovem-e-investir-na-qualidade-da-velhice', destination: '/blog/cuidar-da-saude-desde-jovem-e-investir-na-qualidade-da-velhice', permanent: true },
  { source: '/bancos-de-leite-humano-solidariedade-que-salva-vidas', destination: '/blog/bancos-de-leite-humano-solidariedade-que-salva-vidas', permanent: true },
  { source: '/semana-nacional-da-pessoa-com-deficiencia-intelectual-e-multipla-conscientizacao-e-inclusao-em-foco', destination: '/blog/semana-nacional-da-pessoa-com-deficiencia-intelectual-e-multipla-conscientizacao-e-inclusao-em-foco', permanent: true },
  { source: '/anacli-reafirma-excelencia-com-acreditacao-dicq', destination: '/blog/anacli-reafirma-excelencia-com-acreditacao-dicq', permanent: true },
  { source: '/amamentacao-nutrir-com-amor-e-garantir-saude-desde-o-inicio-da-vida', destination: '/blog/amamentacao-nutrir-com-amor-e-garantir-saude-desde-o-inicio-da-vida', permanent: true },
  { source: '/colesterol-alto-acoes-essenciais-para-a-saude-cardiovascular', destination: '/blog/colesterol-alto-acoes-essenciais-para-a-saude-cardiovascular', permanent: true },
  { source: '/agosto-azul-mes-de-conscientizacao-sobre-a-saude-do-homem', destination: '/blog/agosto-azul-mes-de-conscientizacao-sobre-a-saude-do-homem', permanent: true },
  { source: '/amamentar-e-um-ato-de-cuidado-saude-conexao-e-amor', destination: '/blog/amamentar-e-um-ato-de-cuidado-saude-conexao-e-amor', permanent: true },
  { source: '/a-importancia-dos-exames-laboratoriais-para-a-saude-do-homem', destination: '/blog/a-importancia-dos-exames-laboratoriais-para-a-saude-do-homem', permanent: true },
  { source: '/seu-colesterol-pode-estar-te-sabotando', destination: '/blog/seu-colesterol-pode-estar-te-sabotando', permanent: true },
  { source: '/dia-nacional-de-luta-das-pessoas-com-deficiencia-direitos-e-desafios', destination: '/blog/dia-nacional-de-luta-das-pessoas-com-deficiencia-direitos-e-desafios', permanent: true },
  { source: '/anacli-e-certificado-pelo-gptw-como-uma-das-melhores-empresas-para-trabalhar-em-2025', destination: '/blog/anacli-e-certificado-pelo-gptw-como-uma-das-melhores-empresas-para-trabalhar-em-2025', permanent: true },
  { source: '/anacli-oferece-exame-molecular-de-hpv-e-reforca-prevencao-do-cancer-de-colo-uterino', destination: '/blog/anacli-oferece-exame-molecular-de-hpv-e-reforca-prevencao-do-cancer-de-colo-uterino', permanent: true },
  { source: '/agir-salva-vidas-prevencao-ao-suicidio-em-foco', destination: '/blog/agir-salva-vidas-prevencao-ao-suicidio-em-foco', permanent: true },
  { source: '/composicao-sanguinea-entenda-os-principais-componentes', destination: '/blog/composicao-sanguinea-entenda-os-principais-componentes', permanent: true },
  { source: '/por-que-os-exames-de-rotina-fazem-tanta-diferenca', destination: '/blog/por-que-os-exames-de-rotina-fazem-tanta-diferenca', permanent: true },
  { source: '/dia-do-medico-gratidao-a-quem-cuida-da-vida', destination: '/blog/dia-do-medico-gratidao-a-quem-cuida-da-vida', permanent: true },
  { source: '/saude-mental-em-foco-a-criacao-de-um-dia-mundial', destination: '/blog/saude-mental-em-foco-a-criacao-de-um-dia-mundial', permanent: true },
  { source: '/outubro-rosa-um-mes-dedicado-a-prevencao-e-ao-cuidado-da-mulher', destination: '/blog/outubro-rosa-um-mes-dedicado-a-prevencao-e-ao-cuidado-da-mulher', permanent: true },
  { source: '/outubro-verde-conscientizacao-sobre-a-sifilis-e-a-sifilis-congenita', destination: '/blog/outubro-verde-conscientizacao-sobre-a-sifilis-e-a-sifilis-congenita', permanent: true },
  { source: '/vacinacao-protecao-para-todos', destination: '/blog/vacinacao-protecao-para-todos', permanent: true },
  { source: '/exames-de-sangue-que-ajudam-a-detectar-doencas-silenciosas', destination: '/blog/exames-de-sangue-que-ajudam-a-detectar-doencas-silenciosas', permanent: true },
  { source: '/mitos-e-verdades-sobre-o-colesterol-entenda-os-riscos-e-cuidados', destination: '/blog/mitos-e-verdades-sobre-o-colesterol-entenda-os-riscos-e-cuidados', permanent: true },
  { source: '/jejum-para-exames-quando-e-realmente-necessario', destination: '/blog/jejum-para-exames-quando-e-realmente-necessario', permanent: true },
  { source: '/cuide-do-seu-coracao-faca-um-check-up-e-mantenha-a-saude-em-dia', destination: '/blog/cuide-do-seu-coracao-faca-um-check-up-e-mantenha-a-saude-em-dia', permanent: true },
  { source: '/exame-de-urina-o-que-ele-revela-sobre-sua-saude', destination: '/blog/exame-de-urina-o-que-ele-revela-sobre-sua-saude', permanent: true },
  { source: '/como-a-tecnologia-garante-mais-precisao-nos-exames-laboratoriais', destination: '/blog/como-a-tecnologia-garante-mais-precisao-nos-exames-laboratoriais', permanent: true },
  { source: '/mito-ou-verdade-so-precisa-fazer-mamografia-depois-dos-50-anos', destination: '/blog/mito-ou-verdade-so-precisa-fazer-mamografia-depois-dos-50-anos', permanent: true },
  { source: '/doacao-de-sangue-um-gesto-simples-que-salva-vidas', destination: '/blog/doacao-de-sangue-um-gesto-simples-que-salva-vidas', permanent: true },
  { source: '/novembro-azul-conscientizacao-e-prevencao-para-a-saude-do-homem', destination: '/blog/novembro-azul-conscientizacao-e-prevencao-para-a-saude-do-homem', permanent: true },
  { source: '/exames-essenciais-para-cuidar-da-saude-do-homem', destination: '/blog/exames-essenciais-para-cuidar-da-saude-do-homem', permanent: true },
  { source: '/entenda-a-importancia-do-hemograma-completo-para-a-sua-saude', destination: '/blog/entenda-a-importancia-do-hemograma-completo-para-a-sua-saude', permanent: true },
  { source: '/dia-mundial-do-diabetes-pequenas-atitudes-que-fazem-grande-diferenca', destination: '/blog/dia-mundial-do-diabetes-pequenas-atitudes-que-fazem-grande-diferenca', permanent: true },
  { source: '/chegou-o-verao-dicas-para-curtir-a-estacao-mais-quente-com-saude-e-bem-estar', destination: '/blog/chegou-o-verao-dicas-para-curtir-a-estacao-mais-quente-com-saude-e-bem-estar', permanent: true },
  { source: '/dezembro-vermelho-reforca-conscientizacao-e-prevencao-do-hiv-aids', destination: '/blog/dezembro-vermelho-reforca-conscientizacao-e-prevencao-do-hiv-aids', permanent: true },
  { source: '/dia-internacional-da-pessoa-com-deficiencia-reforca-inclusao-e-direitos', destination: '/blog/dia-internacional-da-pessoa-com-deficiencia-reforca-inclusao-e-direitos', permanent: true },
  { source: '/verao-com-saude-quais-exames-fazer-antes-de-viajar', destination: '/blog/verao-com-saude-quais-exames-fazer-antes-de-viajar', permanent: true },
  { source: '/alimentacao-e-exames-laboratoriais-o-que-pode-alterar-os-resultados', destination: '/blog/alimentacao-e-exames-laboratoriais-o-que-pode-alterar-os-resultados', permanent: true },
  { source: '/cancer-de-mama-sintomas-e-sinais-de-alerta-que-nao-podem-ser-ignorados', destination: '/blog/cancer-de-mama-sintomas-e-sinais-de-alerta-que-nao-podem-ser-ignorados', permanent: true },
  { source: '/prevencao-comeca-em-casa-sinais-de-alerta-para-procurar-um-medico', destination: '/blog/prevencao-comeca-em-casa-sinais-de-alerta-para-procurar-um-medico', permanent: true },
  { source: '/laboratorio-anacli-conquista-acreditacao-em-gestao-da-qualidade', destination: '/blog/laboratorio-anacli-conquista-acreditacao-em-gestao-da-qualidade', permanent: true },
  { source: '/intolerancia-a-lactose-entenda-como-funciona-o-exame-e-quando-fazer', destination: '/blog/intolerancia-a-lactose-entenda-como-funciona-o-exame-e-quando-fazer', permanent: true },
  { source: '/anacli-um-ano-de-dedicacao-a-voce', destination: '/blog/anacli-um-ano-de-dedicacao-a-voce', permanent: true },
  { source: '/entenda-a-importancia-da-vitamina-d-para-o-organismo', destination: '/blog/entenda-a-importancia-da-vitamina-d-para-o-organismo', permanent: true },
  { source: '/anacli-gratidao-conquistas-e-esperanca-para-o-novo-ano', destination: '/blog/anacli-gratidao-conquistas-e-esperanca-para-o-novo-ano', permanent: true },
  { source: '/anacli-gratidao-conquistas-e-esperanca-para-o-novo-ano-2', destination: '/blog/anacli-gratidao-conquistas-e-esperanca-para-o-novo-ano-2', permanent: true },
  { source: '/janeiro-branco-cuidar-da-mente-tambem-e-cuidar-do-corpo', destination: '/blog/janeiro-branco-cuidar-da-mente-tambem-e-cuidar-do-corpo', permanent: true },
  { source: '/verao-e-saude-atencao-redobrada-com-hidratacao-e-exames', destination: '/blog/verao-e-saude-atencao-redobrada-com-hidratacao-e-exames', permanent: true },
  { source: '/check-up-prevencao-comeca-with-exames-em-dia', destination: '/blog/check-up-prevencao-comeca-with-exames-em-dia', permanent: true },
  { source: '/doencas-comuns-no-verao-quando-procurar-o-laboratorio', destination: '/blog/doencas-comuns-no-verao-quando-procurar-o-laboratorio', permanent: true },
  { source: '/dia-internacional-do-hanseniano-informacao-que-salva-vidas', destination: '/blog/dia-internacional-do-hanseniano-informacao-que-salva-vidas', permanent: true },
  { source: '/alteracoes-no-sono-e-no-humor-sinais-de-alerta', destination: '/blog/alteracoes-no-sono-e-no-humor-sinais-de-alerta', permanent: true },
  { source: '/doencas-silenciosas-o-que-os-exames-revelam', destination: '/blog/doencas-silenciosas-o-que-os-exames-revelam', permanent: true },
  { source: '/vitaminas-e-minerais-quando-a-deficiencia-pode-ser-detectada-em-exames', destination: '/blog/vitaminas-e-minerais-quando-a-deficiencia-pode-ser-detectada-em-exames', permanent: true },
  { source: '/a-importancia-da-hidratacao-para-a-saude-2', destination: '/blog/a-importancia-da-hidratacao-para-a-saude-2', permanent: true },
  { source: '/fevereiro-roxo-e-laranja-chama-atenca', destination: '/blog/fevereiro-roxo-e-laranja-chama-atenca', permanent: true }
    ];
  },
  images: {
    formats: ['image/avif', 'image/webp'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'scontent-bsb1-1.cdninstagram.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'lh3.googleusercontent.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'via.placeholder.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'cms.anacli.com.br',
        port: '',
        pathname: '/**',
      }
    ],
    dangerouslyAllowSVG: true,
    contentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;",
  },
  poweredByHeader: false,
  compress: true,
}

module.exports = nextConfig